Favorites Fragment not showing list
Error: No adapter attached; skipping layout

Adapter isn't attaching to the recyclerview. We can grab data successfully, but for some reason it's not being added to the local list created.